### ISSUE TITLE
sample usage for iOS

### ISSUE THREAD

**Issue by kiszadr** [ayoubdev/react-native-responsive#3]
hello,
have you got more examples for iOS, e.g. for iPhone 6s, iPad, iPod?
Regards

**Comment by ColeTownsend** [comment]
Hey @kiszadr it might be helpful to reference the google [device metrics table](https://material.io/devices/) which includes dimensions. Based on the example in the readme, you can formulate any query.

I added a more explicit example in my PR for creating media query variables to reuse. https://github.com/aybadb/react-native-responsive/pull/4/files

**Comment by kiszadr** [comment]
Hey,
thank you very much. I will take a look on your example and revert you if I'll have more questions.

Thanks and regards
